web:
  build: .
  ports:
  - 8081:80
  volumes:
  - ./worldapi:/opt/www/worldapi
  links:
  - db:mysql
db:
  image: mysql:5.6
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw
    MYSQL_DATABASE: homestead
    MYSQL_USER: homestead
    MYSQL_PASSWORD: secret
